name: API Test Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: 'Manual Run'

permissions:
    contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Deploy API container
        run: |
          docker pull coherentsolutions/rest-training:2.0
          docker run -d -p 5544:8082 coherentsolutions/rest-training:2.0
          # Wait for container to be ready
          sleep 10

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: '21'


      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.3

      - name: Build and run tests with Maven
        run: mvn test
        continue-on-error: true

      - name: Check test results
        run: |
          if [ -d "target/surefire-reports" ] && [ "$(find target/surefire-reports -name '*.xml' | wc -l)" -gt 0 ]; then
            echo "Tests were run"
            grep -r -i "failures=\"[1-9]" target/surefire-reports/*.xml && exit 1 || echo "All tests passed"
          else
            echo "No test results found"
            exit 1
          fi

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-results/**/*.xml
            test-results/**/*.trx
            test-results/**/*.json    
            
            permissions:
              checks: write
              pull-requests: write     
