name: API Test Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: 'Manual Run'

permissions:
  checks: write
  pull-requests: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Deploy API container
        run: |
          docker pull coherentsolutions/rest-training:2.0
          docker run -d -p 5544:8082 coherentsolutions/rest-training:2.0
          # Wait for container to be ready
          sleep 10

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: '21'


      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.3

      - name: Build and run tests with Maven
        run: mvn clean test
        continue-on-error: true
        
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          retention-days: 90
          name: target
          path: |
            ${{ github.workspace }}/target/surefire-reports
            ${{ github.workspace }}/target/allure-results
            ${{ github.workspace }}/allure-results

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: target
          path: ${{ github.workspace }}/target
      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Build test report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          allure_results: target/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: allure-results
          publish_dir: allure-history

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-results/**/*.xml
            test-results/**/*.trx
            test-results/**/*.json
            target/surefire-reports/*.xml
           
